import Header from '../components/Header';
import './globals.css';


export const metadata = {
  title: 'AI Travel Planner - Plan Your Next Adventure',
  description: 'Generate customizable daily itineraries, budget estimations, and lodging options in a few simple clicks.',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-brand-50 flex flex-col">
        <Header />
        <main className="flex-1 w-full max-w-6xl mx-auto px-4 py-8">
          {children}
        </main>
        <footer className="bg-white border-t border-brand-200 py-6 text-center text-xs text-slate-500 mt-auto">
          <div className="max-w-6xl mx-auto px-4">
            <p>© {new Date().getFullYear()} AI Travel Planner. Handcrafted with care. All travel data is generated by AI.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
